### PR TITLE
Fixed few typos

### PR DESCRIPTION
**Pull request by sarvsav**
This PR fixed some typos and grammar mistakes.

### CODE REVIEW

**Review by Soypete — DISMISSED** [review]

**Comment by sarvsav** [comment]
@Soypete may I request your review again? :)

**Review by Soypete — APPROVED** [review]

**Comment by sarvsav** [comment]
@Soypete May I request for your help on how can I verify the previous commits that were not signed and pushed 2 years back?

**Comment by Soypete** [comment]
I will merge now if you  are ok with the changes

**Comment by sarvsav** [comment]
Yes, if it's okay for you. I will make the next PRs with signed commits.

**Pull request merged**
